import Head from 'next/head';
import Image from 'next/image';

export default function Index() {
  return (
    <>
      <Head>
        <title>Next.js Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>microcmsの画像↓（成功)</p>
      <div style={{ position: 'relative', width: 500, height: 500 }}>
        <Image
          src="https://images.microcms-assets.io/assets/a24ee35ca7ca4996a3ecf74c5e3799ea/9a92b1fd5c5242a7ac9a10331b4d678a/pickles.jpg"
          alt=""
          layout="fill"
          objectFit="cover"
          priority={true}
        />
      </div>

      <p>newtの画像↓（失敗）</p>
      <div style={{ position: 'relative', width: 500, height: 500 }}>
        <Image
          src="https://storage.googleapis.com/p_63038f276ebb912e9b4c73f5/8233b9e8-dbf4-44ad-881e-19d875776ef3%2Fsample02.jpg"
          alt=""
          layout="fill"
          objectFit="cover"
          priority={true}
        />
      </div>
    </>
  );
}
